// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCM0hVMpBTNQWt8cBMNyygqGPKF_Rwwrgo',
    appId: '1:39485904573:web:ec2427089e0c25a19009d4',
    messagingSenderId: '39485904573',
    projectId: 'flux-16716',
    authDomain: 'flux-16716.firebaseapp.com',
    storageBucket: 'flux-16716.firebasestorage.app',
    measurementId: 'G-H0HXNJ2CJ7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2IN8NuqABiP-H4bPEXvSi55-UbrOU79s',
    appId: '1:39485904573:android:8fba850b9df01feb9009d4',
    messagingSenderId: '39485904573',
    projectId: 'flux-16716',
    storageBucket: 'flux-16716.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4cyWv4h3mrMNIaCf2XdLFzZ5m66B0uk4',
    appId: '1:39485904573:ios:00251b9cf1531ca19009d4',
    messagingSenderId: '39485904573',
    projectId: 'flux-16716',
    storageBucket: 'flux-16716.firebasestorage.app',
    androidClientId: '39485904573-1tk4grcsgodbj6qai1i2b7jvgqvbe5h1.apps.googleusercontent.com',
    iosClientId: '39485904573-k02ueq5cv8nqoa1i8lup0llkhkodikg3.apps.googleusercontent.com',
    iosBundleId: 'com.example.easaccFirstTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4cyWv4h3mrMNIaCf2XdLFzZ5m66B0uk4',
    appId: '1:39485904573:ios:00251b9cf1531ca19009d4',
    messagingSenderId: '39485904573',
    projectId: 'flux-16716',
    storageBucket: 'flux-16716.firebasestorage.app',
    androidClientId: '39485904573-1tk4grcsgodbj6qai1i2b7jvgqvbe5h1.apps.googleusercontent.com',
    iosClientId: '39485904573-k02ueq5cv8nqoa1i8lup0llkhkodikg3.apps.googleusercontent.com',
    iosBundleId: 'com.example.easaccFirstTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCM0hVMpBTNQWt8cBMNyygqGPKF_Rwwrgo',
    appId: '1:39485904573:web:52c51f15ea62779a9009d4',
    messagingSenderId: '39485904573',
    projectId: 'flux-16716',
    authDomain: 'flux-16716.firebaseapp.com',
    storageBucket: 'flux-16716.firebasestorage.app',
    measurementId: 'G-JP1G8020RJ',
  );

}